// Map country display name -> ISO 3166-1 alpha-2 code (lowercase), used for flag images
export const COUNTRY_ISO2: Record<string, string> = {
  "United States": "us",
  USA: "us",
  US: "us",
  Australia: "au",
  Ireland: "ie",
  Germany: "de",
  Romania: "ro",
  Japan: "jp",
  "United Kingdom": "gb",
  UK: "gb",
  "Great Britain": "gb",
  Canada: "ca",
  France: "fr",
  Israel: "il",
  Russia: "ru",
  Iran: "ir",
  Turkey: "tr",
  India: "in",
  Brazil: "br",
  Poland: "pl",
  Ukraine: "ua",
  Netherlands: "nl",
  Sweden: "se",
  Spain: "es",
  Italy: "it",
  Egypt: "eg",
  "South Africa": "za",
  Indonesia: "id",
  Malaysia: "my",
  Pakistan: "pk",
  Jordan: "jo",
  Lebanon: "lb",
  Norway: "no",
  Denmark: "dk",
  Finland: "fi",
  Belgium: "be",
  Austria: "at",
  Switzerland: "ch",
  Greece: "gr",
  Portugal: "pt",
  Mexico: "mx",
  Argentina: "ar",
  China: "cn",
  "Saudi Arabia": "sa",
  "United Arab Emirates": "ae",
  Syria: "sy",
  Iraq: "iq",
  Qatar: "qa",
  "South Korea": "kr",
  "North Korea": "kp",
  Czechia: "cz",
  "Czech Republic": "cz",
};

export const getCountryIso2 = (name?: string | null): string | null => {
  if (!name) return null;
  return COUNTRY_ISO2[name] || null;
};

// Map ISO-3 country codes (used by world topojson) to display names
export const ISO3_TO_NAME: Record<string, string> = {
  USA: "United States",
  AUS: "Australia",
  IRL: "Ireland",
  DEU: "Germany",
  ROU: "Romania",
  JPN: "Japan",
  GBR: "United Kingdom",
  CAN: "Canada",
  FRA: "France",
  ISR: "Israel",
  RUS: "Russia",
  IRN: "Iran",
  TUR: "Turkey",
  IND: "India",
  BRA: "Brazil",
  POL: "Poland",
  UKR: "Ukraine",
  NLD: "Netherlands",
  SWE: "Sweden",
  ESP: "Spain",
  ITA: "Italy",
  EGY: "Egypt",
  ZAF: "South Africa",
  IDN: "Indonesia",
  MYS: "Malaysia",
  PAK: "Pakistan",
  JOR: "Jordan",
  LBN: "Lebanon",
  NOR: "Norway",
  DNK: "Denmark",
  FIN: "Finland",
  BEL: "Belgium",
  AUT: "Austria",
  CHE: "Switzerland",
  GRC: "Greece",
  PRT: "Portugal",
  MEX: "Mexico",
  ARG: "Argentina",
  CHN: "China",
  SAU: "Saudi Arabia",
  ARE: "United Arab Emirates",
  SYR: "Syria",
  IRQ: "Iraq",
  QAT: "Qatar",
};
