name: Dev Deploy

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  packages: write

concurrency:
  group: dev-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      ENVIRONMENT_NAME: dev
